-- Supabase chain menu rollout: tables for chain_menu_profiles and chain_menu_items.
-- Run this in the Supabase SQL Editor (Dashboard → SQL Editor → New query).
-- Requires public schema; adjust schema if your project uses a different one.

-- 1. Chain menu profiles (one row per chain + market)
create table if not exists public.chain_menu_profiles (
  id bigint generated by default as identity primary key,
  chain_key text not null,
  market_tag text not null,
  brand_name text,
  source_url text,
  source_type text,
  store_name_variants jsonb default '[]',
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique (chain_key, market_tag)
);

comment on table public.chain_menu_profiles is 'Chain profile per market for Supabase-backed chain menus';
comment on column public.chain_menu_profiles.store_name_variants is 'JSON array of name variants for matching';

-- 2. Chain menu items (many per chain + market)
create table if not exists public.chain_menu_items (
  id bigint generated by default as identity primary key,
  chain_key text not null,
  market_tag text not null,
  item_key text not null,
  item_name text,
  category text,
  estimated_calories int,
  estimated_protein_g int,
  estimated_carbs_g int,
  estimated_fat_g int,
  vegetarian_possible boolean default false,
  vegan_possible boolean default false,
  confidence numeric(5,2),
  negative_flags jsonb default '[]',
  menu_item_source text,
  source_url text,
  protein_density_score numeric(10,2),
  fat_loss_fit_score numeric(10,2),
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique (chain_key, market_tag, item_key)
);

comment on table public.chain_menu_items is 'Chain menu items per chain + market for Healthy Nearby enrichment';

-- Optional: refresh updated_at on row update (if your table already exists and errors on upsert)
-- alter table public.chain_menu_profiles alter column updated_at set default now();
-- create or replace function public.chain_menu_profiles_updated_at()
-- returns trigger as $$ begin new.updated_at = now(); return new; end; $$ language plpgsql;
-- drop trigger if exists chain_menu_profiles_updated_at on public.chain_menu_profiles;
-- create trigger chain_menu_profiles_updated_at before update on public.chain_menu_profiles
--   for each row execute function public.chain_menu_profiles_updated_at();

-- Optional: RLS (enable if you use RLS; service role bypasses RLS by default)
-- alter table public.chain_menu_profiles enable row level security;
-- alter table public.chain_menu_items enable row level security;
-- create policy "Allow service role full access to chain_menu_profiles" on public.chain_menu_profiles for all using (true) with check (true);
-- create policy "Allow service role full access to chain_menu_items" on public.chain_menu_items for all using (true) with check (true);
