-- Create venue_contributions for CalorieClick.ai local venue feedback.
-- Apply via Supabase Management API or SQL editor against project ref mgrwrthvhjpmbrvmvkeo.

create table if not exists public.venue_contributions (
  id bigint generated by default as identity primary key,
  contribution_id text not null unique,
  place_id text,
  place_name text not null,
  area_key text not null,
  contribution_type text not null,
  user_id text,
  payload jsonb,
  status text not null default 'pending',
  created_at timestamptz not null default now(),
  reviewed_at timestamptz,
  reviewer_id text,
  reviewer_notes text,
  constraint venue_contributions_contribution_type_check
    check (
      contribution_type in (
        'better_order_suggestion',
        'item_not_on_menu',
        'vegetarian_option_missing',
        'vegan_option_missing',
        'recommendation_accurate',
        'recommendation_inaccurate',
        'menu_item_correction'
      )
    ),
  constraint venue_contributions_status_check
    check (status in ('pending', 'accepted', 'rejected'))
);

grant usage on schema public to service_role;
grant all on table public.venue_contributions to service_role;
grant usage, select on sequence public.venue_contributions_id_seq to service_role;

alter table public.venue_contributions enable row level security;

drop policy if exists "service_role_full_access_venue_contributions" on public.venue_contributions;
create policy "service_role_full_access_venue_contributions"
on public.venue_contributions
for all
to service_role
using (true)
with check (true);

