-- Create user_scan_contributions for shared meal scan nutrition feedback.
-- Apply via Supabase Management API or SQL editor against project ref mgrwrthvhjpmbrvmvkeo.

create table if not exists public.user_scan_contributions (
  id bigint generated by default as identity primary key,
  user_id text not null,
  place_name text,
  place_id text,
  items jsonb not null default '[]'::jsonb,
  total_kcal numeric,
  source text not null default 'meal_photo_scan',
  created_at timestamptz not null default now()
);

create index if not exists idx_user_scan_contributions_user_id
  on public.user_scan_contributions (user_id);

create index if not exists idx_user_scan_contributions_created_at
  on public.user_scan_contributions (created_at desc);

grant usage on schema public to service_role;
grant all on table public.user_scan_contributions to service_role;
grant usage, select on sequence public.user_scan_contributions_id_seq to service_role;

alter table public.user_scan_contributions enable row level security;

drop policy if exists "service_role_full_access_user_scan_contributions" on public.user_scan_contributions;
create policy "service_role_full_access_user_scan_contributions"
on public.user_scan_contributions
for all
to service_role
using (true)
with check (true);
