-- Cron-ingested items — persists across Railway deploys
-- Scheduler writes here, app merges on startup

create table if not exists public.cron_ingested_items (
  id bigint generated by default as identity primary key,
  chain_key text not null,
  market text not null,
  item_name text not null,
  estimated_calories integer,
  estimated_protein_g numeric,
  estimated_carbs_g numeric,
  estimated_fat_g numeric,
  menu_item_source text default 'real_menu',
  category text,
  protein_per_100kcal numeric,
  raw_payload jsonb,
  created_at timestamptz not null default now(),
  constraint cron_ingested_unique unique (chain_key, market, item_name)
);

alter table public.cron_ingested_items enable row level security;
create policy "service_role_full_access_cron_ingested"
on public.cron_ingested_items for all to service_role using (true) with check (true);

create index if not exists idx_cron_ingested_chain on public.cron_ingested_items(chain_key, market);
